export const APPLICATION_JAVASCRIPT = 'application/javascript'
export const APPLICATION_JSON = 'application/json'
export const APPLICATION_LD_PLUS_JSON = 'application/ld+json'
export const APPLICATION_PDF = 'application/pdf'
export const APPLICATION_RTF = 'application/rtf'
export const APPLICATION_TYPESCRIPT = 'application/typescript'
export const APPLICATION_X_JAVASCRIPT = 'application/x-javascript'
export const APPLICATION_X_NS_PROXY_AUTOCONFIG = 'application/x-ns-proxy-autoconfig'
export const APPLICATION_X_TYPESCRIPT = 'application/x-typescript'
export const APPLICATION_X_X509_CA_CERT = 'application/x-x509-ca-cert'
export const APPLICATION_X_X509_USER_CERT = 'application/x-x509-user-cert'
export const APPLICATION_XHTML_PLUS_XML = 'application/xhtml+xml'
export const APPLICATION_XML = 'application/xml'

export const FONT_OTF = 'font/otf'
export const FONT_TTF = 'font/ttf'
export const FONT_WOFF = 'font/woff'
export const FONT_WOFF2 = 'font/woff2'

export const IMAGE_APNG = 'image/apng'
export const IMAGE_AVIF = 'image/avif'
export const IMAGE_BMP = 'image/bmp'
export const IMAGE_GIF = 'image/gif'
export const IMAGE_JPEG = 'image/jpeg'
export const IMAGE_PNG = 'image/png'
export const IMAGE_SVG = 'image/svg'
export const IMAGE_SVG_PLUS_XML = 'image/svg+xml'
export const IMAGE_TIFF = 'image/tiff'

export const TEXT_CALENDAR = 'text/calendar'
export const TEXT_CSS = 'text/css'
export const TEXT_CSV = 'text/csv'
export const TEXT_HTML = 'text/html'
export const TEXT_JAVASCRIPT = 'text/javascript'
export const TEXT_JSON = 'text/json'
export const TEXT_PLAIN = 'text/plain'
export const TEXT_XML = 'text/xml'
